export default [
    "¿Cuáles son los principales desafíos en la protección de la privacidad en la era digital?",
    "¿Cómo afecta la recopilación de datos personales a los derechos digitales?",
    "¿Cuáles son los límites entre la libertad de expresión en línea y el discurso de odio?",
    "¿Qué medidas se pueden tomar para prevenir la censura en Internet?",
    "¿Cómo se pueden proteger los derechos de propiedad intelectual en la era digital?",
    "¿Qué implicaciones tiene la inteligencia artificial en los derechos digitales?",
    "¿Cuál es el papel de los gobiernos en la protección de los derechos digitales de los ciudadanos?",
    "¿Cómo se pueden abordar los desafíos de la desinformación en línea sin afectar la libertad de expresión?",
    "¿Debería haber límites en el monitoreo y la vigilancia en línea por parte de los gobiernos?",
    "¿Cuáles son los derechos digitales de los niños y cómo se pueden proteger?",
    "¿Qué medidas se pueden tomar para garantizar la neutralidad de la red?",
    "¿Debería existir un 'derecho al olvido' en Internet?",
    "¿Cuál es la responsabilidad de las plataformas de redes sociales en la protección de los derechos digitales?",
    "¿Cómo se puede abordar el acoso y el abuso en línea sin restringir la libertad de expresión?",
    "¿Cuáles son los riesgos y beneficios de la biometría y el reconocimiento facial en términos de derechos digitales?",
    "¿Qué implicaciones tienen las tecnologías de vigilancia masiva en los derechos a la privacidad y la libertad?",
    "¿Debería haber más regulación en el uso de algoritmos y sistemas de inteligencia artificial?",
    "¿Cómo se pueden garantizar los derechos digitales de las personas con discapacidades?",
    "¿Qué medidas se pueden tomar para proteger los derechos digitales durante los períodos de crisis, como pandemias o situaciones de emergencia?",
    "¿Deberían existir normas internacionales para proteger los derechos digitales?",
    "¿Cuál es el impacto de la publicidad personalizada en los derechos de privacidad de los usuarios?",
    "¿Cuál es el equilibrio adecuado entre la seguridad y la privacidad en la era digital?",
    "¿Cómo se pueden abordar los desafíos de la propiedad de los datos personales en línea?",
    "¿Deberían los usuarios tener el derecho de acceder, corregir y eliminar sus datos personales en línea?",
    "¿Cómo se puede garantizar la igualdad de acceso a la tecnología y los servicios digitales?",
    "¿Qué implicaciones tiene el uso de drones y tecnologías de vigilancia en los derechos a la privacidad y la libertad?",
    "¿Deberían las plataformas de redes sociales ser responsables de la moderación de contenido ilegal o perjudicial?",
    "¿Qué derechos digitales están en riesgo debido a la adopción de tecnologías de inteligencia artificial y automatización?",
    "¿Cuál es el papel de la educación digital en la protección de los derechos digitales?",
    "¿Deberían los gobiernos regular el uso de criptomonedas para garantizar la seguridad y la privacidad?",
    "¿Cómo se pueden proteger los derechos de los trabajadores en la economía digital?",
    "¿Cuál es el impacto de la geolocalización y el seguimiento en línea en la privacidad y los derechos digitales?",
    "¿Deberían los usuarios tener el derecho de saber cómo se utilizan sus datos personales en línea?",
    "¿Qué implicaciones tiene el uso de algoritmos en la toma de decisiones automatizadas para los derechos digitales?",
    "¿Cómo se puede garantizar la seguridad de la información personal en línea?",
    "¿Cuál es el impacto de las tecnologías de reconocimiento facial en la privacidad y los derechos civiles?",
    "¿Debería haber más transparencia en los algoritmos utilizados por las plataformas en línea?",
    "¿Qué medidas se pueden tomar para prevenir el robo de identidad en línea?",
    "¿Cuál es el papel de las organizaciones internacionales en la protección de los derechos digitales a nivel global?",
    "¿Deberían existir límites en la recopilación de datos por parte de empresas privadas?",
    "¿Cuál es el impacto de la vigilancia en línea en la libertad de expresión y la democracia?",
    "¿Qué implicaciones tiene la inteligencia artificial en la discriminación y la equidad?",
    "¿Deberían los usuarios tener el derecho de ser informados sobre cómo se utilizan los datos recopilados en línea?",
    "¿Cómo se pueden abordar los desafíos de la seguridad cibernética sin comprometer los derechos digitales?",
    "¿Cuál es el impacto de las tecnologías de realidad virtual y aumentada en los derechos digitales?",
    "¿Debería existir una regulación más estricta sobre la publicidad en línea dirigida a niños?",
    "¿Qué medidas se pueden tomar para prevenir el acoso en línea y proteger los derechos de las víctimas?",
    "¿Cuál es el impacto de la inteligencia artificial en el empleo y los derechos laborales?",
    "¿Deberían existir límites en la retención de datos por parte de las empresas en línea?",
    "¿Qué implicaciones tiene el acceso limitado a Internet en los derechos digitales de las comunidades marginadas?"
]

